source "https://rubygems.org"
gemspec

gem "jekyll", "~> 4.3.3"

gem "jekyll-github-metadata", ">= 2.15"

gem "jekyll-include-cache", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development
