name: test-api

# Environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main


      # Run Pester tests
      - name: Test GitHub API auth
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          if (Test-Path -Path "env:GITHUB_TOKEN") {
            $Token = $True
            $TokenValue = $env:GITHUB_TOKEN
          }
          elseif (Test-Path -Path "env:GH_TOKEN") {
              $Token = $True
              $TokenValue = $env:GH_TOKEN
          }
          $Headers = @{
              Authorization = "token $TokenValue"
          }
          $params = @{
              Uri     = "https://api.github.com/rate_limit"
              Headers = $Headers
          }
          $response = Invoke-RestMethod @params
          $response.resources.core
          $response.rate
