name: test-output

# Environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  update-pwsh:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: Evergreen
          shell: pwsh

      # Import GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPGKEY }}
          passphrase: ${{ secrets.GPGPASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
          git_committer_name: ${{ secrets.COMMIT_NAME }}
          git_committer_email: ${{ secrets.COMMIT_EMAIL }}

      # Run Pester tests
      - name: Update versions
        shell: pwsh
        run: |
          . "${{ github.workspace }}/Update-Versions.ps1" -Path "${{ github.workspace }}/json"

      # Format the date number for the commit message
      - name: Get date
        id: get-date
        run: |
            DATEF=`date +%Y.%m.%d`
            echo "::set-output name=date::$DATEF"

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update json ${{ steps.get-date.outputs.date }}.${{ github.run_number }}"
          commit_user_name: ${{ secrets.COMMIT_NAME }}
          commit_user_email: ${{ secrets.COMMIT_EMAIL }}

      - name: "Run if changes have been detected"
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Changes committed."

      - name: "Run if no changes have been detected"
        if: steps.commit.outputs.changes_detected == 'false'
        run: echo "No changes detected."

  update-powershell:
      needs: update-pwsh
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
          with:
            ref: main

        # Run Pester tests
        - name: Update versions
          shell: powershell
          run: |
            git config --global core.safecrlf false
            git pull origin main

        - name: Install and cache PowerShell modules
          id: psmodulecache
          uses: potatoqualitee/psmodulecache@v4.5
          with:
            modules-to-cache: Evergreen
            shell: powershell

        # Import GPG key
        - name: Import GPG key
          id: import_gpg
          uses: crazy-max/ghaction-import-gpg@v4
          with:
            gpg_private_key: ${{ secrets.GPGKEY }}
            passphrase: ${{ secrets.GPGPASSPHRASE }}
            git_user_signingkey: true
            git_commit_gpgsign: true
            git_config_global: true
            git_tag_gpgsign: true
            git_push_gpgsign: false
            git_committer_name: ${{ secrets.COMMIT_NAME }}
            git_committer_email: ${{ secrets.COMMIT_EMAIL }}

        # Run Pester tests
        - name: Update versions
          shell: powershell
          run: |
            . "${{ github.workspace }}/Update-Versions.ps1" -Path "${{ github.workspace }}/json"

        # Format the date number for the commit message
        - name: Get date
          id: get-date
          run: |
            echo "::set-output name=date::$(Get-Date -Format "yyyy.MM.dd")"

        - name: Commit changes
          id: commit
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Update json ${{ steps.get-date.outputs.date }}.${{ github.run_number }}"
            commit_user_name: ${{ secrets.COMMIT_NAME }}
            commit_user_email: ${{ secrets.COMMIT_EMAIL }}

        - name: "Run if changes have been detected"
          if: steps.commit.outputs.changes_detected == 'true'
          run: echo "Changes committed."

        - name: "Run if no changes have been detected"
          if: steps.commit.outputs.changes_detected == 'false'
          run: echo "No changes detected."
