name: Update-CloudflareWorkersKV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "json/*.json"

jobs:
  update-kv:
    runs-on: ubuntu-latest
    name: update

    steps:
      - uses: actions/checkout@v2

      - name: wrangler
        id: update
        shell: pwsh
        run: |
          cd "${{ github.workspace }}/json"
          npm install -g wrangler
          foreach ($file in (Get-ChildItem -Path "*.json")) {    
            wrangler kv:key put $file.BaseName.ToLower() --path=$($file.FullName) --namespace-id="${{secrets.KV_PROD_NAMESPACE_ID}}"
          }

        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}

