# Update JSON via my self-hosted runner
name: update-selfhosted

# Environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "5 11 * * *"

jobs:
  update-pwsh:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install modules
        shell: pwsh
        run: |
          Install-Module -Name "Evergreen", "DnsClient-PS" -Force

      # Import GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPGKEY }}
          passphrase: ${{ secrets.GPGPASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
          git_committer_name: ${{ secrets.COMMIT_NAME }}
          git_committer_email: ${{ secrets.COMMIT_EMAIL }}

      # Run Pester tests
      - name: Update app JSON
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          . "${{ github.workspace }}/scripts/Update-JsonHosted.ps1" -Path "${{ github.workspace }}/json"

      # Format the date number for the commit message
      - name: Get date
        id: get-date
        shell: pwsh
        run: |
          $Date = Get-Date -Format "yyyy.MM.dd"
          echo "date=$Date" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update json ${{ steps.get-date.outputs.date }}.${{ github.run_number }} ${{ github.job }}"
          commit_user_name: ${{ secrets.COMMIT_NAME }}
          commit_user_email: ${{ secrets.COMMIT_EMAIL }}

      - name: "Run if changes have been detected"
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Changes committed."

      - name: "Run if no changes have been detected"
        if: steps.commit.outputs.changes_detected == 'false'
        run: echo "No changes detected."
